In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [13]:
## Define the vocabulary size
voc_size = 10000

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### one hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[9324, 2781, 9487, 4866],
 [9324, 2781, 9487, 5604],
 [9324, 8548, 9487, 1265],
 [6431, 873, 2637, 5860, 1351],
 [6431, 873, 2637, 5860, 1438],
 [2857, 9324, 3915, 9487, 1940],
 [2756, 8828, 6303, 5860]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences ## it is used make the length of sentences equall
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [14]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9324 2781 9487 4866]
 [   0    0    0    0 9324 2781 9487 5604]
 [   0    0    0    0 9324 8548 9487 1265]
 [   0    0    0 6431  873 2637 5860 1351]
 [   0    0    0 6431  873 2637 5860 1438]
 [   0    0    0 2857 9324 3915 9487 1940]
 [   0    0    0    0 2756 8828 6303 5860]]


In [15]:
## feature representation
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\Guru nanak\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step


array([[[-0.03057665, -0.04848671, -0.04977634,  0.00253129,
          0.04721442,  0.02938124, -0.01014711, -0.00689236,
          0.03180405, -0.02359151],
        [-0.03057665, -0.04848671, -0.04977634,  0.00253129,
          0.04721442,  0.02938124, -0.01014711, -0.00689236,
          0.03180405, -0.02359151],
        [-0.03057665, -0.04848671, -0.04977634,  0.00253129,
          0.04721442,  0.02938124, -0.01014711, -0.00689236,
          0.03180405, -0.02359151],
        [-0.03057665, -0.04848671, -0.04977634,  0.00253129,
          0.04721442,  0.02938124, -0.01014711, -0.00689236,
          0.03180405, -0.02359151],
        [ 0.03818674,  0.0436607 ,  0.00979298,  0.01206351,
          0.00949787,  0.00898521, -0.03616264, -0.03152031,
          0.03506536,  0.02662163],
        [ 0.00934615, -0.0018798 , -0.01461012, -0.04159464,
          0.00615026, -0.00974723,  0.04798594, -0.02903721,
         -0.02507257,  0.00664929],
        [ 0.03152225, -0.04309067,  0.04452724, -0.0

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 9324, 2781, 9487, 4866], dtype=int32)

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0, 9324, 2781, 9487, 4866], dtype=int32)

In [20]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 423ms/step


array([[ 0.02939863, -0.04140357, -0.01658082,  0.04572744, -0.01138126,
         0.01974479, -0.03493104, -0.04400961,  0.01664034,  0.04547851],
       [ 0.02939863, -0.04140357, -0.01658082,  0.04572744, -0.01138126,
         0.01974479, -0.03493104, -0.04400961,  0.01664034,  0.04547851],
       [ 0.02939863, -0.04140357, -0.01658082,  0.04572744, -0.01138126,
         0.01974479, -0.03493104, -0.04400961,  0.01664034,  0.04547851],
       [ 0.02939863, -0.04140357, -0.01658082,  0.04572744, -0.01138126,
         0.01974479, -0.03493104, -0.04400961,  0.01664034,  0.04547851],
       [-0.03707885,  0.03141688,  0.04773215, -0.04473023, -0.02833679,
        -0.04914988,  0.00351607, -0.01074228,  0.03569091,  0.04010652],
       [ 0.02496726,  0.01140423,  0.03181953, -0.00934447, -0.00428536,
        -0.03929455, -0.01079096,  0.0232198 ,  0.00592568,  0.02211608],
       [-0.04623478,  0.02753149, -0.01252228,  0.01025429,  0.0479946 ,
        -0.01245947,  0.03680335, -0.040763  